//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAppEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbHumanResourceEntities : DbContext
    {
        public dbHumanResourceEntities()
            : base("name=dbHumanResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblEmployeeInfo> tblEmployeeInfoes { get; set; }
        public virtual DbSet<tblEmployeeLeave> tblEmployeeLeaves { get; set; }
        public virtual DbSet<tblsalary> tblsalaries { get; set; }
        public virtual DbSet<tblUserdetail> tblUserdetails { get; set; }
    }
}
