//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAppEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployeeInfo()
        {
            this.tblEmployeeLeaves = new HashSet<tblEmployeeLeave>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeLeave> tblEmployeeLeaves { get; set; }
    }
}
