//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAppEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeLeave
    {
        public int EmployeeID { get; set; }
        public System.DateTime LeaveStartDate { get; set; }
        public System.DateTime LeaveEndDate { get; set; }
        public string LeaveReason { get; set; }
        public string LeaveType { get; set; }
    
        public virtual tblEmployeeInfo tblEmployeeInfo { get; set; }
    }
}
