//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAppEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsalary
    {
        public int salid { get; set; }
        public Nullable<double> basi { get; set; }
        public Nullable<double> hra { get; set; }
        public Nullable<double> da { get; set; }
        public Nullable<double> deductions { get; set; }
    }
}
