//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_PROJECT_Tome_Books_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookDetail()
        {
            this.BookAvailabilities = new HashSet<BookAvailability>();
            this.CartDetails = new HashSet<CartDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.RatingDetails = new HashSet<RatingDetail>();
        }
    
        public int bookID { get; set; }
        public string ISBN { get; set; }
        public int authorID { get; set; }
        public int publisherID { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
        public string edition { get; set; }
        public string bookName { get; set; }
        public string bookType { get; set; }
        public string language { get; set; }
        public decimal bookPrice { get; set; }
        public string description { get; set; }
        public string photoPath { get; set; }
        public string dimension { get; set; }
        public int viewCount { get; set; }
        public int subcategoryID { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAvailability> BookAvailabilities { get; set; }
        public virtual PublisherDetail PublisherDetail { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingDetail> RatingDetails { get; set; }
    }
}
