//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_PROJECT_Tome_Books_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookAvailability
    {
        public int BookAvailabilityID { get; set; }
        public int bookID { get; set; }
        public int supplierID { get; set; }
        public decimal rentalPrice { get; set; }
        public int actualAvailability { get; set; }
        public int currentAvailability { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
