//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_PROJECT_Tome_Books_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackDetail
    {
        public int feedbackID { get; set; }
        public int userID { get; set; }
        public System.DateTime feedbackdate { get; set; }
        public string subject { get; set; }
        public string feedback { get; set; }
    
        public virtual User User { get; set; }
    }
}
