//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_PROJECT_Tome_Books_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipDetail
    {
        public int membershipDetailsID { get; set; }
        public int membershipID { get; set; }
        public int userID { get; set; }
        public Nullable<System.DateTime> planFromDate { get; set; }
        public Nullable<System.DateTime> planToDate { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual User User { get; set; }
    }
}
