//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_PROJECT_Tome_Books_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailsID { get; set; }
        public int orderID { get; set; }
        public int bookID { get; set; }
        public int quantity { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
        public virtual Order Order { get; set; }
    }
}
