//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_PROJECT_Tome_Books_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int orderID { get; set; }
        public int userID { get; set; }
        public int shipperID { get; set; }
        public int supplierID { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public System.DateTime lendingDate { get; set; }
        public System.DateTime returnDate { get; set; }
        public Nullable<System.DateTime> actualReturnDate { get; set; }
        public Nullable<int> borrowExtendedDays { get; set; }
        public decimal totalPrice { get; set; }
        public int totalQuantity { get; set; }
        public Nullable<int> discountID { get; set; }
        public string orderStatus { get; set; }
    
        public virtual Discount Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
    }
}
